version: "3.5"
services:
  website:
    build:
      context: .
      dockerfile: ./website/Dockerfile
    command: yarn start:prod
    ports:
      - 3000:3000
    volumes:
      - ./website:/app
      - /app/node_modules
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start:prod
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
